### ISSUE TITLE
macOS 10.14.3 GUI wallet bug

### ISSUE THREAD

**Issue by xiant9** [jojapoppa/fedoragold-wallet-electron#1]
I get an error when attempting to create a new wallet on macOS 10.14.3
![Screen Shot 2019-03-10 at 4 33 07 PM](https://user-images.githubusercontent.com/46408129/54092495-6c9b3100-4352-11e9-845e-e903965590c4.png)
. Please see the attached screenshot.

**Comment by robotsoutofcontrol** [comment]
Hi Xiant, it looks like you are using an older version of the Mac wallet. But if you want to wait we are also building some UX enhancements into all the wallets - should be fairly soon.

I'll ping you when they are live if you like?

**Comment by xiant9** [comment]
I am happy to wait, or I am also happy to try a more update version that would work. Either way, please let me know. Thanks.

**Comment by xiant9** [comment]
Also, is there a way to take the downloaded blockchain on windows and migrate it over to Mac? Or do you have a downloadable bootstrap?

**Comment by robotsoutofcontrol** [comment]
Hi @xiant9 we have updated the Mac wallet - try this version please and let us know if that resolves your issue:

https://www.dropbox.com/s/9erbuonvbzuy3sl/FedoraGoldWallet-v1.0.6-mac.zip?dl=1

**Comment by xiant9** [comment]
Thank you for that link. Unfortunately I am still getting the same error:

![Screen Shot 2019-03-10 at 10 25 27 PM](https://user-images.githubusercontent.com/46408129/54100324-8a34be80-4383-11e9-87e3-68f1b0d023df.png)

**Comment by robotsoutofcontrol** [comment]
Sorry Xiant! What version Mac OS are you on? It needs High Sierra minimum

**Comment by xiant9** [comment]
I am running the latest version- macOS 10.14.3 (Mojave). The one after High Sierra.

**Comment by jojapoppa** [comment]
Howdy Xiant,
Can you please try creating your wallet with a wallet name (not Untitled)?  Perhaps that's the trouble...
Thanks!!!!!
Jojapoppa

**Comment by xiant9** [comment]
I have tried many different names, passwords, and file paths. Nothing works. I even created a wallet on a windows computer, and transferred the wallet to my Mac. The Mac version will not open it. I tried exporting the keys from the windows wallet and importing them on the Mac version... will not work. I get a similar red box of death 💀 + error message.

**Comment by jojapoppa** [comment]
Humm.  

What if you run Applications/Utilities/Terminal and then type in this:

/Applications/FedoraGoldWallet.app/Contents/Resources/bin/mac/fedoragold_walletd --container-file /Users/christian/test.wal --container-password 123 --log-level 0 --generate-container

tx
joja

**Comment by xiant9** [comment]
Illegal Instruction: 4

![Screen Shot 2019-03-12 at 9 11 41 AM](https://user-images.githubusercontent.com/46408129/54211459-fbb95d80-44a6-11e9-8383-9078bcf3f410.png)

**Comment by jojapoppa** [comment]
Very helpful.  tx.

**Comment by robotsoutofcontrol** [comment]
Hi Xiant - please get the very latest Mac build here we believe this will solve the issue:

https://www.dropbox.com/s/c6p350cys1pnrzg/FedoraGoldWalletMac-v1.0.7.zip?dl=0

**Comment by xiant9** [comment]
We are making progress... but it is still not working. I am able to create a wallet now, although it still gives me an error. I cannot open the wallet because it claims I am not using the right password. I have uploaded two screen shots plus the wallet file. I know I am using the right password because it is: 1234.
[fedoragoldTEST.wal.zip](https://github.com/jojapoppa/fedoragold-wallet-electron/files/2967133/fedoragoldTEST.wal.zip)
![Screen Shot 2019-03-14 at 9 18 52 AM](https://user-images.githubusercontent.com/46408129/54369001-c3e31f00-463a-11e9-8c54-e64a7ea5e29c.png)
![Screen Shot 2019-03-14 at 9 19 21 AM](https://user-images.githubusercontent.com/46408129/54369002-c3e31f00-463a-11e9-8314-bd026285d2b9.png)

**Comment by robotsoutofcontrol** [comment]
Hi Jojapoppa, is it possible that there is some password validation logic that requires a certain length password, but the logic is only applied when opening and not creating? That might explain the bug Xiant is experiencing.

**Comment by xiant9** [comment]
I should state that I have tried an 8 character Alphanumeric password. I just did not want to screen shot it.

**Comment by jojapoppa** [comment]
thanks.  i'm looking at this right now...

**Comment by jojapoppa** [comment]
Hi Xiant,
I found the bug.  If you close your wallet, and open it again from scratch, the password should work.  I will issue a patch shortly, but can you please try that?
Thanks!!

**Comment by xiant9** [comment]
I just did exactly what you asked and I still get the same error with the latest version.

**Comment by jojapoppa** [comment]
ok

**Comment by robotsoutofcontrol** [comment]
Hi Xiant - Jojapoppa has released an updated version which we hope resolves the issue - please use this link:

https://www.dropbox.com/s/cadhpdiqkoawmsx/FedoraGoldWallet-v1.0.8-mac.zip?dl=0

**Comment by xiant9** [comment]
I am sorry to report that 1.0.8 has the same issues and does not open an existing wallet nor does it allow me to access/open a newly created wallet.

**Comment by xiant9** [comment]
I get the exact same errors as my previous comment: https://github.com/jojapoppa/fedoragold-wallet-electron/issues/1#issuecomment-472916173

**Comment by xiant9** [comment]
I tried to run the daemon binary and received the following:

![Screen Shot 2019-03-17 at 11 49 47 PM](https://user-images.githubusercontent.com/46408129/54509531-76eb9b00-490f-11e9-9e03-b8ba9965f030.png)

**Comment by jojapoppa** [comment]
okay, i'm looking at this again right now...

**Comment by robotsoutofcontrol** [comment]
Hi Xiant - please try this version. Thanks again for your patience and help!

https://www.dropbox.com/s/7ravaojaruk7eet/FedoraGoldWallet-v1.0.9-mac.zip?dl=1

**Comment by xiant9** [comment]
Same error, except now it is NOT creating the wallet after displaying error message.

**Comment by robotsoutofcontrol** [comment]
Hi Xiant - if you don't mind trying again Joja has updated: https://www.dropbox.com/s/31vqgy6ruw4em6y/FedoraGoldWallet-v1.1.0-mac.zip?dl=1

**Comment by xiant9** [comment]
I am still getting the command failed error but it is back to creating the wallet file regardless of the error message. If I try to manually open the wallet I get the "Failed to load your wallet, please heck your password" error. Is it possible that it is not even adding a password to the file because the command fails?

**Comment by jojapoppa** [comment]
Sorry, for the tedium xiant9... but could you please post a screenshot?  Also, we will be paying you a bug bounty for sure btw... tx!

**Comment by xiant9** [comment]
Running the daemon does not work. Please se attached screen shots:

![Screen Shot 2019-03-19 at 8 40 45 AM](https://user-images.githubusercontent.com/46408129/54615166-3bda8c00-4a23-11e9-9eb4-a95a30de8f82.png)
![Screen Shot 2019-03-19 at 8 42 03 AM](https://user-images.githubusercontent.com/46408129/54615177-43019a00-4a23-11e9-8d0c-4672384a5005.png)

![Screen Shot 2019-03-19 at 8 41 14 AM](https://user-images.githubusercontent.com/46408129/54615234-56ad0080-4a23-11e9-99cf-534e67489434.png)

**Comment by xiant9** [comment]
Forgot daemon screen shot:

![Screen Shot 2019-03-19 at 8 47 37 AM](https://user-images.githubusercontent.com/46408129/54615430-b6a3a700-4a23-11e9-8e84-4a1da7127ce9.png)

**Comment by jojapoppa** [comment]
Hi.  Do you have either Intego or Kaspersky installed?  tx.

**Comment by xiant9** [comment]
I do not have either one installed.

**Comment by xiant9** [comment]
Is there a CLI Mac version that I could attempt to compile on my system to see if I can get the daemon to work?

**Comment by jojapoppa** [comment]
I can compile one for you... but i was just going to upload another attempt soon.  If you hang in there with me and help me kill this bug... i will pay you 100,000 FED.  ;-)

**Comment by xiant9** [comment]
I’m happy to hang in there!! I just wish I could do more to help.

**Comment by jojapoppa** [comment]
You're already doing a lot.  I'm sorry our team wasn't able to replicate this on our end... multiple macs all work... so it's worth it to debug your situation..  Eventually we will get it for sure!

**Comment by jojapoppa** [comment]
I put some text in the error messages in this build that can show me where the problem is... I also added symbols so that it may give you a stack trace.... additionally I tried bumping the min version supported to 10.12, and I also added a 5 second timeout when calling the walletd and daemon from Electron.
Robots will post it soon.  tx!!

**Comment by robotsoutofcontrol** [comment]
Hi Xiant, here's the latest build with the debug settings updated to help resolve. Thank you again!

https://www.dropbox.com/s/wggs5zanbx6vfvl/FedoraGoldWallet-v1.1.1-mac.zip?dl=1

**Comment by xiant9** [comment]
Same problems... Here are the screen shots plus I upload files that might be useful.

![Screen Shot 2019-03-20 at 8 33 41 AM](https://user-images.githubusercontent.com/46408129/54693334-0a79c300-4aec-11e9-8c30-221e5ec53cc3.png)
![Screen Shot 2019-03-20 at 8 34 25 AM](https://user-images.githubusercontent.com/46408129/54693342-0ea5e080-4aec-11e9-8946-358b1d8fdf3c.png)
![Screen Shot 2019-03-20 at 8 37 21 AM](https://user-images.githubusercontent.com/46408129/54693347-11a0d100-4aec-11e9-9f6d-10e9ec40b3f2.png)
[FedoraGold macOS Bug.zip](https://github.com/jojapoppa/fedoragold-wallet-electron/files/2988706/FedoraGold.macOS.Bug.zip)

**Comment by jojapoppa** [comment]
This was super helpful.  Thank you. I will update the build, and have robots post an update in a bit.  i have added some more debug information into the output again...tx

**Comment by robotsoutofcontrol** [comment]
Hi Xiant! Please try this one

https://www.dropbox.com/s/xgguqjy2n004g0r/FedoraGoldWallet-v1.1.2-mac.zip?dl=1

**Comment by xiant9** [comment]
We are back to not creating the wallet with the error:

![Screen Shot 2019-03-20 at 10 45 06 PM](https://user-images.githubusercontent.com/46408129/54733959-451e4280-4b62-11e9-8c53-742457dc9a10.png)

**Comment by robotsoutofcontrol** [comment]
Hi Xiant,
I have an idea - if it's not too much trouble that is! How would you feel about making a virtual Mac instance on something like VirtualBox please? My thinking is - start with a fresh vanilla Mac that has no history of any kind.

Then - we try installing the wallet onto that instance and see how it works. There's one small risk I see - VirtualBox will probably inherit your network settings on your current Mac, and it could be the network settings that are the issue.  

The other possible way of exploring it is to create a cloud based Mac - but these don't seem to be readily available. So trying on VirtualBox might be the best approach. It should be free of other issues.

I firmly agree with Joja's offer of a bug bounty by the way - we could always chat in Telegram privately regarding that - do you have the Fedora Telegram address?

Cheers!
Robots.

**Comment by xiant9** [comment]
I will see what I can do. What is the telegram address? I would like to chat about that.

**Comment by jojapoppa** [comment]
yes, Telegram would help a lot.  My Telegram username is @jojapoppa

**Comment by robotsoutofcontrol** [comment]
Hi Xiant - I've created a Telegram group just for Fedora QA - we'd love to have you join: https://t.me/joinchat/G697bBTUWd0eOJWPdYlQuA

**Comment by robotsoutofcontrol** [comment]
Hi Xiant - please feel free to jump into the Telegram chat (see link above) when you can :-)

**Comment by xiant9** [comment]
Hello there. I must admit I have lost motivation with this. I will try and setup a new Mac for testing soon. Cheers

**Comment by robotsoutofcontrol** [comment]
Hi Xiant! I completely understand - you have helped a HUGE amount entirely generously of your own time, and we are extremely grateful!

We actually wanted to flag something with you - hence the Telegram group, but I'll share here. Are you by any chance interested in being involved with the project on a closer level? You seem to have a solid understanding of QA & issue resolution - are you an engineer or QA specialist?

**Comment by robotsoutofcontrol** [comment]
It would be easier to chat in private in the Telegram re that though :-)

**Comment by xiant9** [comment]
Tgram: @Xian999

**Comment by robotsoutofcontrol** [comment]
Hi Xian jump in here: https://t.me/joinchat/G697bBTUWd0eOJWPdYlQuA :-)

**Comment by xiant9** [comment]
Completely different Mac, fresh install of macOS 10.14.4. At least now we are getting a new error (more detailed) during the wallet creation. I am still getting the dreaded illegal instruction 4 when trying to execute the daemon.

![Screen Shot 2019-04-07 at 9 49 39 PM](https://user-images.githubusercontent.com/46408129/55697906-b17dac00-5980-11e9-9d76-1b16af797eeb.png)
![Screen Shot 2019-04-07 at 9 50 43 PM](https://user-images.githubusercontent.com/46408129/55697907-b17dac00-5980-11e9-82fd-303828e3149d.png)

**Comment by xiant9** [comment]
Good luck!
