### ISSUE TITLE
Send Screen/Transaction Sent Message/Explorer Link Broken

### ISSUE THREAD

**Issue by robotsoutofcontrol** [jojapoppa/fedoragold-wallet-electron#44]
1. When sending a transaction, the Send screen displays a Transaction Sent message
2. The message contains a link to the FED Explorer to view the transaction
3. The link retains the port 8080 suffix, this causes the link to break.
4. Need to remove ":8080" from the URL path

**Comment by jojapoppa** [comment]
fixed.

**Comment by jojapoppa** [comment]
fixed in v2.0.2
