### ISSUE TITLE
Transaction Timeout - Actually showing in Error

### ISSUE THREAD

**Issue by robotsoutofcontrol** [jojapoppa/fedoragold-wallet-electron#45]
I believe that the wallet has a timeout setting where it thinks a transaction fails, but in fact the transaction has succeeded. There have been several cases where the wallet displayed the timeout image, but recipients subsequently told me that they received their coins. I think the timeout message is linked to a hard ref data value that does not in fact capture an actual transaction failure, just a heuristic of what it **_thinks failure is_**.

![image](https://user-images.githubusercontent.com/4340080/71780158-33375e80-3013-11ea-9db1-7bbc5a84966a.png)

**Comment by jojapoppa** [comment]
This message displays when there is a network error during the send process.  I have verified it by simulating those conditions.  I did alter the error message, to tell people to verify the transaction by looking at the Transaction History screen, as most of the time the transactions DO complete properly.

**Comment by jojapoppa** [comment]
fixed in v2.0.2
