### ISSUE TITLE
Wallet link to explorer has bug

### ISSUE THREAD

**Issue by robotsoutofcontrol** [jojapoppa/fedoragold-wallet-electron#5]
The link from the wallet (off the "transaction complete" screen) goes to an incorrect URL for the Fedora Gold block explorer

The following sample transaction hash illustrates the right/wrong ways of configuring the link.

**Current (wrong) link:**
http://explorer.fedoragold.com/?hash=cc84128c002a9041629cba09ca274037ab63e4af4cc5011f04d07ef55661c4de#blockchain_transaction

**What it should be:**
http://explorer.fedoragold.com/gettransaction.php?hash=cc84128c002a9041629cba09ca274037ab63e4af4cc5011f04d07ef55661c4de

**The exact wallet screen where the link is placed (in the green panel):**
![image](https://user-images.githubusercontent.com/4340080/56627589-d3b64000-6689-11e9-97bc-30c7171f8ba4.png)

**Comment by robotsoutofcontrol** [comment]
I've located where the error is - it's in ws_config.js, line 27.  Link to file is below, under where I've pasted the invalid line:

// block explorer url, the [[TX_HASH] will be substituted w/ actual transaction hash
config.blockExplorerUrl = 'http://explorer.fedoragold.com/?hash=[[TX_HASH]]#blockchain_transaction';

https://github.com/jojapoppa/fedoragold-wallet-electron/blob/master/src/js/ws_config.js

**Comment by jojapoppa** [comment]
tx... fixed.

**Comment by jojapoppa** [comment]
fixed... thanks for the detailed post... made it easy.  cheers...
