### ISSUE TITLE
Text entry field overflow error

### ISSUE THREAD

**Issue by robotsoutofcontrol** [jojapoppa/fedoragold-wallet-electron#9]
If you overflow the wallet address text entry field on "Send Transaction" it disables the "Payment ID" entry field. Wallet must close & restart completely to re-enable the "Payment ID" field.

Easiest way to recreate it is to just paste the wallet address twice.

I'd suggest it's a LOW priority - nobody has reported it, I'm just odd :)

![image](https://user-images.githubusercontent.com/4340080/59156440-aeb54980-8ade-11e9-9988-93fa98987d2c.png)

**Comment by jojapoppa** [comment]
Fixed in v2.0.3
